server:
  port: 8082

db:
  host: aws-0-ap-southeast-1.pooler.supabase.com
  port: 5432
  user: postgres.iqejnxlcibjlwofjdjcc
  password: 9csX26xyIrxPVt88
  dbname: postgres
  sslmode: require
  pool_mode: session
  timezone: Asia/Bangkok
